export default [
    {
        uuid:"app_demo",
        icon:"",
        name:"测试应用",
        description:"用于测试的一个应用",
        i18n:true,
        languageSupport:["zh-cn","en-us"],
        pages:{
            Page_Default:"home",
            Page_404:"404"
        },
        i18nName:[
            {
                lang:"zh-cn",
                content:"测试应用"
            },{
                lang:"en-us",
                content:"Test App"
            }
        ],
        i18nDescription:[
            {
                lang:"zh-cn",
                content:"用于测试的一个应用"
            },{
                lang:"en-us",
                content:"Just for Test."
            }
        ]
    },{
        uuid:"app_demo_2",
        icon:"",
        name:"测试应用2",
        description:"用于测试的一个应用",
        i18n:true,
        languageSupport:["zh-cn","en-us"],
        pages:{
            Page_Default:"home",
            Page_404:"404"
        },
        i18nName:[
            {
                lang:"zh-cn",
                content:"测试应用"
            },{
                lang:"en-us",
                content:"Test App"
            }
        ],
        i18nDescription:[
            {
                lang:"zh-cn",
                content:"用于测试的一个应用"
            },{
                lang:"en-us",
                content:"Just for Test."
            }
        ]
    }
];