export default {
	/*
	内置变量_是否编辑状态
	内置变量_所处终端
	内置变量_当前语言
	内置变量_路径
	内置变量_Query
	内置变量_路由参数
	内置变量_hash
	内置变量_屏幕高度
	内置变量_屏幕宽度
	内置变量_localStorage
	内置变量_sessionStorage
	内置变量_navigator
	*/
	internalVar:[
		{
			uuid:"internal_is_edit_status",
			varShowName:"内置变量_是否编辑状态",
			varCodeName:"Is_Edit_Status",
			varDataType:"Boolean",
			varDataDesc:{},
			defaultValue:null
		}
	],


	//内置函数
	internalFunc:[
		{
			uuid:"",
			funcShowName:"内置函数_打开链接",
			funcCodeName:"OpenUrl",
			params:[
				{
					varShowName:"URL地址",
					varCodeName:"url",
					dataType:"String"
				}
			],
			returnDataType:null
		},{
			uuid:"",
			funcShowName:"内置函数_显示组件",
			funcCodeName:"showView",
			params:[
				{
					varShowName:"组件UUID",
					varCodeName:"viewUUID",
					dataType:"String"
				}
			],
			returnDataType:null
		},{
			uuid:"",
			funcShowName:"内置函数_隐藏组件",
			funcCodeName:"hideView",
			params:[
				{
					varShowName:"组件UUID",
					varCodeName:"viewUUID",
					dataType:"String"
				}
			],
			returnDataType:null
		}
	]
};