var ui = {
	uuid:"ui_1",
	appUUID:"app_1234",
	title:"测试页面",
	status:"Dev",
	description:"这是一个测试DSL",
	icon:"", //待定
	view:{
		uuid:"view_1",
		name:"页面",
		component:"m-page",
		category:"Container",

		attributes:[],
		styles:[],
		events:[],

		children:[
			{
				uuid:"view_1_1",
				name:"文本1",
				component:"m-text",
				category:"Single",
				attributes:{},
				style:{},
				events:{},
			},{
				uuid:"view_1_2",
				name:"数据表格1",
				component:"m-table",
				category:"Single",
				attributes:{
					ds:{
						uuid:"data_1",
						inputConfig:[
							{
								varName:"param1",
								varValue:"var1"
							},{
								varName:"param2",
								varValue:"{{自定义变量_XXX}}"
							},{
								varName:"param3",
								varValue:"{{内置变量_query['param3']}}"
							}
						],
						outputConfig:{
							varName: "userList"
						}
					},
					fields:[
						{}
					]
				},
				styles:{},
				actions:{},
			}
		],
		modals:[
			{}
		]
	},
	customVars:[],
	customFuncs:[]
}