var ui = {
	uuid:"ui_1",
	title:"测试页面",
	status:"Dev",
	description:"这是一个测试DSL",
	icon:"", //待定
	view:{
		uuid:"view_1",
		name:"页面",
		component:"m-page",
		category:"Container",
		layouts:"",//待定
		attributes:{},
		style:{},
		events:{},
		children:[
			{
				uuid:"view_1_1",
				name:"文本1",
				component:"m-text",
				category:"Single",
				attributes:{},
				style:{},
				events:{},
			},{
				uuid:"view_1_2",
				name:"数据表格1",
				component:"m-table",
				category:"Single",
				attributes:{
					ds:{
						uuid:"data_1",
						inputConfig:[
							{
								valName:"param1",
								valValue:"val1"
							},{
								valName:"param2",
								valValue:"{{自定义变量_XXX}}"
							},{
								valName:"param3",
								valValue:"{{内置变量_query['param3']}}"
							}
						],
						outputConfig:{
							valName: "userList"
						}
					},
					fields:[
						{}
					]
				},
				style:{},
				events:{},
			}
		],
		modals:[
			{}
		]
	},
	buzzs:{
		val:[
		],
		func:[
		]
	}
}